name = "2000s Edition"
author = "NicSonic"
version = "b1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3c4cad825e927cb69e9cd3ca9626525a20a9f721aebe44f1da4ab6108e19e6a"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
