name = "2000s Edition"
author = "NicSonic-_-"
version = "beta_1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d26348ced0d602447b42831c2405a2b66c9348fa6c912340bf1fc407a8e83ce"

[versions]
fabric = "0.17.3"
minecraft = "1.21.1"
